spring:
  application:
    name: curapaste
  datasource:
    url: jdbc:postgresql://localhost:5432/pastebin
    username: pastebin
    password: pastebin
  jpa:
    hibernate:
        ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
storage:
  endpoint: http://localhost:9000
  access-key: minio
  secret-key: minio123
  bucket: curapaste-content
  region: us-east-
  inline-threshold-bytes:  50 # less for testing, (use 51200 (50kb) for prod)